name: Check

on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: read

concurrency:
  cancel-in-progress: true
  group: check-${{ github.ref }}

jobs:
  check:
    name: Unit Tests & Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Set Up Tools
        uses: jdx/mise-action@v5
        with:
          version: 2026.10.5
      - name: Run Checks
        run: mise run check

  validate-hacs:
    name: HACS
    runs-on: ubuntu-latest
    steps:
      - name: Validate With HACS
        uses: hacs/action@main
        with:
          category: integration

  validate-hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Validate With Hassfest
        uses: home-assistant/actions/hassfest@master
