name: Check

on:
  pull_request:
  push:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  cancel-in-progress: true
  group: check-${{ github.ref }}

jobs:
  check:
    name: Unit tests and Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Set up tools
        uses: jdx/mise-action@v5
        with:
          version: 2026.10.3
      - name: Run checks
        run: mise run check

  validate-hacs:
    name: HACS
    runs-on: ubuntu-latest
    steps:
      - name: Validate with HACS
        uses: hacs/action@main
        with:
          category: integration

  validate-hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Validate with hassfest
        uses: home-assistant/actions/hassfest@master
